apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - clusters:
      selector:
          matchExpressions:
          - key: managedservices.argocd
            operator: Exists
  template:
    metadata:
        name: '{{ .name }}-argocd'
        labels:
            revision: '{{ index .metadata.labels "managedservices.argocd" | default "HEAD" }}'
            kubernetes: '{{ index .metadata.labels "kubernetes.version" }}'
    spec:
        project: 'default'
        source:
            repoURL: 'https://gitlab.com/martijncalker/poc-argocd-kubernetes-applicationsets.git'
            targetRevision: '{{ index .metadata.labels "managedservices.argocd" | default "HEAD" }}'
            path: 'applications/{{ index .metadata.labels "kubernetes.version" }}/argocd/'
        destination:
            server: '{{ .server }}'
            namespace: 'argocd'
        syncPolicy:
            automated:
                prune: true
            syncOptions:
            - CreateNamespace=true
