apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - clusters:
      selector:
          matchLabels:
              managedservices.argocd: '*'
  template:
    metadata:
        name: '{{ .cluster }}-argocd'
        labels:
            revision: '{{default "HEAD" index .metadata.annotations "managedservices.argocd"}}'
            kubernetes: '{{ index .metadata.annotations "kubernetes.version" }}'
    spec:
        project: 'default'
        source:
            repoURL: 'https://gitlab.com/martijncalker/poc-argocd-kubernetes-applicationsets.git'
            targetRevision: '{{default "HEAD" index .metadata.annotations "managedservices.argocd"}}'
            path: 'applications/{{ index .metadata.annotations "kubernetes.version" }}/argocd/'
        destination:
            server: '{{ .server }}'
            namespace: 'argocd'
        syncPolicy:
            automated:
                prune: true
            syncOptions:
            - CreateNamespace=true
