apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
          matchLabels:
              nl.vancalker.managedservices/argocd-install: 'true'
  template:
    metadata:
        name: '{{ name }}-argocd'
        labels:
            revision: '{{ metadata.labels.nl.vancalker.managedservices/kyverno-install-version }}'
    spec:
        project: 'default'
        source:
            repoURL: 'https://gitlab.com/martijncalker/poc-argocd-kubernetes-applicationsets.git'
            targetRevision: '{{ metadata.labels.nl.vancalker.managedservices/argocd-install-version }}'
            path: 'applications/{{ metadata.labels.version }}/argocd/'
        destination:
            server: '{{ server }}'
            namespace: 'argocd'
        syncPolicy:
            automated:
                prune: true
            syncOptions:
            - CreateNamespace=true
