apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - clusters:
      selector:
          matchExpressions:
          - key: managedservices.cert-manager
            operator: Exists
  template:
    metadata:
        name: '{{ .name }}-cert-manager'
        labels:
            revision: '{{ index .metadata.labels "managedservices.cert-manager" | default "HEAD" }}'
            kubernetes: '{{ index .metadata.labels "kubernetes.version" }}'
    spec:
        project: 'default'
        source:
            repoURL: 'https://gitlab.com/martijncalker/poc-argocd-kubernetes-applicationsets.git'
            targetRevision: '{{ index .metadata.labels "managedservices.cert-manager" | default "HEAD" }}'
            path: 'applications/{{ index .metadata.labels "kubernetes.version" }}/cert-manager/'
        destination:
            server: '{{ .server }}'
            namespace: 'cert-manager'
        syncPolicy:
            automated:
                prune: true
            syncOptions:
            - CreateNamespace=true
