apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
          matchLabels:
              nl.vancalker.managedservices/ingress-nginx-install: 'true'
  template:
    metadata:
        name: '{{ cluster.name }}-{{ name }}'
    spec:
        project: 'default'
        source:
            repoURL: 'https://gitlab.com/martijncalker/poc-argocd-kubernetes-applicationsets.git'
            targetRevision: '{{ metadata.labels.nl.vancalker.managedservices/ingress-nginx-version }}'
            path: '/applications/{{ metadata.labels.version }}/ingress-nginx'
        destination:
            server: '{{ server }}'
            namespace: ' {{ path.basename }}'
        syncPolicy:
            automated:
                prune: true
