apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - clusters:
      selector:
          matchExpressions:
          - key: managedservices.nginx
            operator: Exists
  template:
    metadata:
        name: '{{ .name }}-ingress-nginx'
        labels:
            revision: '{{ index .metadata.labels "managedservices.ingress-nginx" | default "HEAD" }}'
            kubernetes: '{{ index .metadata.labels "kubernetes.version" }}'
    spec:
        project: 'default'
        source:
            repoURL: 'https://gitlab.com/martijncalker/poc-argocd-kubernetes-applicationsets.git'
            targetRevision: '{{ index .metadata.labels "managedservices.ingress-nginx" | default "HEAD" }}'
            path: 'applications/{{ index .metadata.labels "kubernetes.version" }}/ingress-nginx/'
        destination:
            server: '{{ .server }}'
            namespace: 'ingress-nginx'
        syncPolicy:
            automated:
                prune: true
            syncOptions:
            - CreateNamespace=true
