apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
          matchLabels:
              nl.vancalker.managedservices.ingress-nginx/install: 'true'
  template:
    metadata:
        name: '{{ name }}-ingress-nginx'
        labels:
            revision: '{{ metadata.labels.nl.vancalker.managedservices.ingress-nginx/version }}'
            kubernetes-version: '{{ metadata.labels.version }}'
    spec:
        project: 'default'
        source:
            repoURL: 'https://gitlab.com/martijncalker/poc-argocd-kubernetes-applicationsets.git'
            targetRevision: '{{ metadata.labels.nl.vancalker.managedservices.ingress-nginx/version }}'
            path: 'applications/{{ metadata.labels.version }}/ingress-nginx/'
        destination:
            server: '{{ server }}'
            namespace: 'ingress-nginx'
        syncPolicy:
            automated:
                prune: true
            syncOptions:
            - CreateNamespace=true
