apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
          matchLabels:
              nl.vancalker.managedservices.kyverno/install: 'true'
  template:
    metadata:
        name: '{{ name }}-kyverno'
        labels:
            revision: '{{ metadata.labels.nl.vancalker.managedservices.kyverno/version }}'
            kubernetes-version: '{{ metadata.labels.version }}'
    spec:
        project: 'default'
        source:
            repoURL: 'https://gitlab.com/martijncalker/poc-argocd-kubernetes-applicationsets.git'
            targetRevision: '{{ metadata.labels.nl.vancalker.managedservices.kyverno/version }}'
            path: 'applications/{{ metadata.labels.version }}/kyverno/'
        destination:
            server: '{{ server }}'
            namespace: 'kyverno'
        syncPolicy:
            automated:
                prune: true
            syncOptions:
            - CreateNamespace=true
