apiVersion: v1
kind: Secret
metadata:
  name: argocd-applicationsets
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.com/martijncalker/poc-argocd-kubernetes-applicationsets.git
